#! /bin/bash


set -e
export OMP_NUM_THREADS=4

# pre-scaled variables
dom_top=${5} #"3000."  # [m]
dom_bottom="0."
nz=${8}           # number of vertical cells
xi0=${7} #50          # [RP/SP]
dtc=5            # [s]
nrp=${13}           # [1000 RP/m3]
lwc=${17}          # [1/10000 kg/m3]
h1=${18}
h2=${19}
iwc=${9} #"0.001"          # [1/100000 kg/m3]5 0.0001
box_area="500"   # [1/100 m2]
wdm=10           # [10**-6 kg/m3]
rt=${16}			 # riming type
vt=3             # terminal velocity: 1) Heymsfield, 2) Khvorostyanov 3) Boehm 
geo=3            # snow geometry: 1: bulk, 2: fillin, 3: similarity

agg=${6}          # 0: no aggregation. 1: Golovin kernel 2: hydrodynamic kernel
dep=${15}            # 0: no diffusion, 1: vapour diffusion
meltt=1           # 0: no melting, 1: melting activated
multt=0          # 0: no ice multiplication, 1: rime splintering
coll_effi=1      # 0:constant, 1:Boehm
very_simple_frag=.FALSE.
coll_kern=${10} #1         #0:Area, 1:Dmax
stick=$3		 # 0: E_s=1, 1: PK97, 2: Connolly12, 3: 0.5*Connolly12
sp_habit=${14}       # 0: mD-relation, 1:habit
IGF=${21}           # 1: IGF according to CL92, 2: updated IGF + all modifications
sp_frag=0        # 0: no fragmentation, 1: fragmentation
atmo=${12}

model_setup=$4
bndtype=${11} #2: xi ~ flux cdf, 3: discrete

timeend=${20}
dt_1dprof=${21}

# name of the experiment

SUFFNAME="${model_setup}_habit${sp_habit}_xi${xi0}_nz${nz}_iwc${iwc}_dtc${dtc}" 
SUFFNAME="${SUFFNAME}_nrp${nrp}_vt${vt}_coll_kern${coll_kern}_at${agg}_stick${stick}_colleffi${coll_effi}_dep${dep}_bndtype${bndtype}"
SUFFNAME="${SUFFNAME}_ba${box_area}_domtop${dom_top}._timeend${timeend}_dt1dpro${dt_1dprof}_atmo${atmo}_ssat${ssat}"


if [ "$1" == "onlyname" ]; then echo ${0##*/}_${SUFFNAME}; exit ; else echo "not_there"; fi

# scaled variables
nrp=$(echo "${nrp}*1000" | bc -l)
lwc=$(echo "${lwc}*0.0001" | bc -l)
iwc=$(echo "${iwc}*0.00001" | bc -l)
ncl=$(echo "${ncl}*0.0001" | bc -l)
nclmass=$(echo "${nclmass}*0.00000000001" | bc -l)
kernsig=$(echo "${kernsig}*0.01" | bc -l)
#nclmass=$(echo "${nclmass}*0.0001" | bc -l)
Dmean=$(echo "${Dmean}*0.000001" | bc -l) #Dmean in mum

wdm=$(echo "${wdm}*0.000001" | bc -l)
box_area=$(echo "${box_area}*0.01" | bc -l)
h1=$(echo "${h1}*100." | bc -l)
h2=$(echo "${h2}*100." | bc -l)
ssat=$(echo "${ssat}*0.001" | bc -l)
#dtc=$(echo "${dtc}*0.1" | bc -l)

THIS_DIR=$(pwd -P)
BASE_DIR=${THIS_DIR%/*}
RUN_DIR=${BASE_DIR}/run

OUT_DIR=${22}/${0##*/}_${SUFFNAME}
echo "Output directory: ${OUT_DIR}"
rm -rf ${OUT_DIR} 
mkdir -p ${OUT_DIR}

# touch a file with Rev. number
if [[ $(git describe 2> /dev/null) ]]; then
  REV=`cd ${BASE_DIR}; git describe`
  touch ${OUT_DIR}/Rev_$REV
else
  echo "WARNING  No Git-Revision file added."
fi


cd ${OUT_DIR}

cp ${BASE_DIR}/build/src/MCSNOW .
cp ${BASE_DIR}/input/* .

# write namelist to file
cat > input.nml <<EOF
test_case_name = ${0##*/}

&general_nml
  msg_level  = 6
  tcase_id   = 105            ! unique test case id
  ini_type   = 2             ! 0: check, 1: box model, 2: 1D model
  bnd_type   = ${bndtype}              ! 0: zero flux, 1: const xi=xi0, 2: xi ~ flux cdf 4: use 2mom for calculating fluxes
  snowgeo_type = ${geo}       ! 1: bulk, 2: fillin, 3: similarity
  nucl_type  = 1              ! 0: off, 1: constant, 2: Meyers scheme
  rime_type  = ${rt}          ! 0: no riming, 1: continuous, 2: stochastic
  multiplication_type = ${multt} ! 0: no ice multiplication, 1: rime splintering
  diffusion_type =${dep}      ! 0: no diffusion, 1: vapour diffusion
  mergeNoTresh  = 1000        ! number of super-particles per cell, if threshold is exceeded, similar particle get merged
  mergeRatioLimit = 0.0      ! mass ratio below which two similar drops get merged
  melt_type  = ${meltt}        ! 0: no melting, 1: melting activated
  time_end   = ${timeend} !36000 !6000. !18000. !36000.         ! [s] end time 36000
  dt_1dprof  = ${dt_1dprof} !600. !60 !600. !1800.          ! [s] time step for output to file ! 60 for trajectories, otherwise 600??
  dt_2dprof  = 600.          ! [s] time step for output to file
   interpol_pp = .True.
/
&sp_nml
  iwc         = ${iwc}      ! [kg/m3] ice water content
  lwc0        = ${lwc}        ! [kg/m3] liquid water content in the 'LWC zone'
  nrp0        = ${nrp}        ! [1/m3] initial number density of ice particles
  xi0         = ${xi0}        ! [1] number of RP per SP
  nu_gam      = ${nugam}      ! [1] gamma distribution exponent
  mu_gam      = ${mugam}           ! [1] generalized gamma distribution exponent 
  maxTotalNoSps = 10240000
  dtc         = ${dtc}        ! [s] time step of collision
  !idtmc       = 1             ! [1] (dtm=dtc/idtmc) dtm is time step of sedi.
  idtgm       = 1             ! [1] (dtg=dtm/idtgc) dtg is time step of cond./depo.
  sigma0      = 0.62          ! kernel density estimation factor
  nclrate     = ${ncl}        ! [SP/s] num. new SP in 'nucleation zone' (1d-model)
  nclmass     = ${nclmass}    !should be 1...e-9 from Joses calculations       ! mean mass of particles after nucleation
  rm          = ${wdm}        ! [m] mean droplet radius in the 1d-model ice particle riming 
  sp_vterm_id = ${vt}         ! 1:Heymsfield, 2:Khvorostyanov, 3: Boehm
  agg_hist    = -1            ! <0: no history, 0: history with near surface sampling, >0: history with the whole domain sampling
  sp_kernel_id = ${agg}       ! 0: no aggregation. 1: Golovin kernel 2: hydrodynamic kernel
  sp_stick_effi =  ${stick}   ! 0: E_s=1, 1: PK97, 2: Connolly12, 3: 0.5*Connolly12
  coll_kern_type = ${coll_kern} ! 0: Area based, 1: Dmax
  sp_habit = ${sp_habit}                ! 0: m-D-relation, 1: habit prediciton
  sp_frag = 0         ! 0: off, 1: Phillips Fragmentation, 2: updated Fragmentation formulation
  iceicebreak_fpm1=0
  iceicebreak_fpm2=0
  
/
&grid_nml
  dom_top    = ${dom_top}     ! [m]  domain top
  dom_bottom = ${dom_bottom}  ! [m]  domain top
  box_area   = ${box_area}    ! [m2] box area (to form quasi 3d domain)
  nz         = ${nz}          ! [1]  number of vertical grid cells
/
&atmo_nml
  atmo_type  = ${atmo}              ! 1: idealized profiles; 2: ECMWF profiles
  ssat       = ${ssat}           ! [1] saturation
  !h1         = ${h1}
  !h2         = ${h2}
  !nh1        = ${nh1} 
  !nh2        = ${nh2}
 !atmofile = ${atmofile} ! name of atmofile
 !IGF_id = ${IGF}           ! 1: IGF of CL92, 2: updated IGF + all modifications
/
 
EOF

# run
time ./MCSNOW

exit 0
